apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-cmd-v1.0
  labels:
    app: store-service-cmd
    version: "1.0"
    environment: development
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: store-service-cmd
      version: "1.0"
      environment: development
  template:
    metadata:
      labels:
        app: store-service-cmd
        version: "1.0"
        environment: development
    spec:
      containers:
        - name: "store-service-cmd-container"
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST
            - name: spring.profiles.active
              value: "development" 
          ports:
            - name: http
              containerPort: 9991
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

