apiVersion: v1
kind: Service
metadata:
  name: store-service-cmd
  namespace: neargrocery-development
  labels:
    app: store-service-cmd
    version: "1.0"
    environment: development
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9991
      protocol: TCP
      name: http
  selector:
    app: store-service-cmd
    version: "1.0"
    environment: development
